### PR TITLE
Dotnetcore20 migration

### PR DESCRIPTION
**Pull request by LaTtEX**
## Migration of serverless-microservice-bootstrap to .NET Core 2.0

Changes include the ff:

- Changing the targets from 'netstandard1.0' to 'netstandard2.0' or 'netcoreapp2.0', where appropriate
- Changed travis and serverless scripts to point to the correct release folders
- Upgraded NuGet package versions to restore .NET Core 2.0 compatible packages
- Updated necessary csproj entries
- Added .gitignore entries for Visual Studio Code

Otherwise there are no major changes to the code, and all scripts were validated to run using existing instructions in the README.MD.

### CODE REVIEW

**Comment by humblelistener** [comment]
@LaTtEX Thanks for the effort. Looks like Travis CI is failing. Also, could you include the screenshot of curl tests in the PR? 
Thanks


 https://travis-ci.org/PageUpPeopleOrg/serverless-microservice-bootstrap/builds/337812893?utm_source=github_status&utm_medium=notification

**Comment by LaTtEX** [comment]
@humblelistener Here's a screenshot of the healthcheck:

image

**Comment by humblelistener** [comment]
Hurray!!! 💯

**Comment by humblelistener** [comment]
@LaTtEX what was that problem with "error linking so" previously when running the lambda?

**Comment by humblelistener** [comment]
This will close #6

**Pull request merged**
